![picture](https://drive.google.com/uc?export=view&id=1CrcB2C9_dflz0W0RCmKiqR7h2nfI-skF)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras.datasets import mnist
from keras.layers import Dense, Flatten, Conv2D, AveragePooling2D
from keras.models import Sequential

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 2s 0us/step


In [ ]:
x_train.shape

(60000, 28, 28)

In [ ]:
#performing reshaping

x_train = x_train.reshape(x_train.shape[0], 28,28, 1)
x_test = x_test.reshape(x_test.shape[0],28,28, 1)

In [ ]:
x_train.shape

(60000, 28, 28, 1)

In [ ]:
# Normalization(MinMax)

x_train = x_train / 255
x_test = x_test / 255 #min max 0-1

In [ ]:
y_train[0]

5

In [ ]:
#One hot Encoding
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

In [ ]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [ ]:
model = Sequential()

model.add(Conv2D(6, kernel_size = (5,5), padding = 'valid', activation='tanh', input_shape = (28,28,1)))
model.add(AveragePooling2D(pool_size= (2,2), strides = 2, padding = 'valid'))

model.add(Conv2D(16, kernel_size = (5,5), padding = 'valid', activation='tanh'))
model.add(AveragePooling2D(pool_size= (2,2), strides = 2, padding = 'valid'))

model.add(Flatten())
model.add(Dense(120, activation='tanh'))
model.add(Dense(84, activation='tanh'))
model.add(Dense(10, activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d (AverageP  (None, 12, 12, 6)        0         
 ooling2D)                                                       
                                                                 
 conv2d_1 (Conv2D)           (None, 8, 8, 16)          2416      
                                                                 
 average_pooling2d_1 (Averag  (None, 4, 4, 16)         0         
 ePooling2D)                                                     
                                                                 
 flatten (Flatten)           (None, 256)               0         
                                                                 
 dense (Dense)               (None, 120)               3

In [ ]:
model.compile(loss = keras.metrics.categorical_crossentropy, optimizer = keras.optimizers.Adam(), metrics = ['accuracy'])

In [ ]:
model.fit(x_train, y_train, batch_size = 128, epochs=10 , verbose= 1, validation_data = (x_test, y_test))

Epoch 1/10
469/469 [==============================] - 13s 6ms/step - loss: 0.3478 - accuracy: 0.9000 - val_loss: 0.1655 - val_accuracy: 0.9524
Epoch 2/10
469/469 [==============================] - 3s 6ms/step - loss: 0.1299 - accuracy: 0.9610 - val_loss: 0.0921 - val_accuracy: 0.9709
Epoch 3/10
469/469 [==============================] - 2s 5ms/step - loss: 0.0842 - accuracy: 0.9747 - val_loss: 0.0702 - val_accuracy: 0.9786
Epoch 4/10
469/469 [==============================] - 2s 5ms/step - loss: 0.0647 - accuracy: 0.9795 - val_loss: 0.0618 - val_accuracy: 0.9804
Epoch 5/10
469/469 [==============================] - 2s 5ms/step - loss: 0.0522 - accuracy: 0.9836 - val_loss: 0.0565 - val_accuracy: 0.9823
Epoch 6/10
469/469 [==============================] - 2s 5ms/step - loss: 0.0416 - accuracy: 0.9870 - val_loss: 0.0483 - val_accuracy: 0.9842
Epoch 7/10
469/469 [==============================] - 3s 6ms/step - loss: 0.0359 - accuracy: 0.9886 - val_loss: 0.0506 - val_accuracy: 0.9826
Epoch

In [ ]:
score = model.evaluate(x_test, y_test)

print('Test loss:', score[0])
print('Test accuracy:', score[1])

313/313 [==============================] - 1s 3ms/step - loss: 0.0407 - accuracy: 0.9870
Test loss: 0.04070543497800827
Test accuracy: 0.9869999885559082


In [ ]:
x_test[9]

array([[[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [ ]:
predictions = model.predict(x_test)

313/313 [==============================] - 1s 2ms/step


In [ ]:
predictions[9]

array([8.3876444e-07, 1.1558568e-08, 2.3077696e-06, 1.5445244e-04,
       6.5894928e-05, 2.7369399e-04, 1.8077884e-07, 4.4534195e-04,
       1.0390789e-04, 9.9895334e-01], dtype=float32)

In [ ]:
import numpy as np
pred_img = np.argmax(predictions[9])
pred_img

9